package com.xx;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Scanner;

import org.apache.commons.io.IOUtils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
    	System.out.println("start-------------");
    	
//    	new App().aa("aaa.txt");
//    	new App().bb("aaa.txt");
    	new App().cc("aaa.txt");
    	
    	
    	System.out.println("finish-------------");
    }
    
    public void aa(String fileName) {
    	ClassLoader loader = getClass().getClassLoader();
    	File file = new File(loader.getResource(fileName).getFile());
    	System.out.println(file.exists());
    	System.out.println(file.getAbsolutePath());
    }
    
    public void bb(String fileName) {
    	StringBuilder result = new StringBuilder("");

    	//Get file from resources folder
    	ClassLoader classLoader = getClass().getClassLoader();
    	File file = new File(classLoader.getResource(fileName).getFile());

    	try (Scanner scanner = new Scanner(file)) {

    		while (scanner.hasNextLine()) {
    			String line = scanner.nextLine();
    			result.append(line).append("\n");
    		}

    		scanner.close();

    	} catch (IOException e) {
    		e.printStackTrace();
    	}

    	System.out.println("result-> " + result.toString());

    }
    
    public void cc(String fileName) {
    	String result = "";

    	ClassLoader classLoader = getClass().getClassLoader();
    	try {
    	    result = IOUtils.toString(classLoader.getResourceAsStream(fileName));
    	    FileOutputStream fos = new FileOutputStream(new File("temp.pem"));
			System.out.println("copy - result - " + IOUtils.copy(classLoader.getResourceAsStream(fileName), fos));
    	} catch (IOException e) {
    		e.printStackTrace();
    	}
    	
    	System.out.println("result-> " + result);
    	
    }
}
